name: Publish

on:
  push:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Hello"
      - run: whoami
      - run: w
      - run: pwd
      - run: ls -al
      - run: ls -al /
      - run: docker --version
      - run: java -version
      - run: python --version
      - run: docker ps
      - run: docker images
      - run: docker run --name nginx -d nginx:alpine
      - run: sleep 5
      - run: docker logs nginx
      - run: docker ps
      - run: docker rm -f nginx