name: Publish

on:
  push:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Hello"
      - run: whoami
      - run: w
      - run: pwd
      - run: ls -al
      - run: ls -al /
      - run: docker --version
      - run: java -version
      - run: python --version